#pragma once
// Auto-generated by tools/gen_osd_font.py --target amt630a — DO NOT EDIT
// UTF-8 codepoint → BGMAP tile-код (RAM-шрифт 0x1C0+). Невідоме → space (0x1C0).

#include <cstdint>

namespace modesp::osd {

inline uint16_t amt630a_cp_to_tile(uint32_t cp) {
    if (cp >= 0x20 && cp <= 0x7E)     return static_cast<uint16_t>(0x1C0u + (cp - 0x20));
    if (cp >= 0x0410 && cp <= 0x044F) return static_cast<uint16_t>(0x220u + (cp - 0x0410));
    switch (cp) {
        case 0x00B0: return 0x21F;
        case 0x0404: return 0x260;
        case 0x0406: return 0x261;
        case 0x0407: return 0x262;
        case 0x0490: return 0x263;
        case 0x0454: return 0x264;
        case 0x0456: return 0x265;
        case 0x0457: return 0x266;
        case 0x0491: return 0x267;
        case 0x00C4: return 0x268;
        case 0x00D6: return 0x269;
        case 0x00DC: return 0x26A;
        case 0x00E4: return 0x26B;
        case 0x00F6: return 0x26C;
        case 0x00FC: return 0x26D;
        case 0x00DF: return 0x26E;
        case 0x0104: return 0x26F;
        case 0x0105: return 0x270;
        case 0x0106: return 0x271;
        case 0x0107: return 0x272;
        case 0x0118: return 0x273;
        case 0x0119: return 0x274;
        case 0x0141: return 0x275;
        case 0x0142: return 0x276;
        case 0x0143: return 0x277;
        case 0x0144: return 0x278;
        case 0x00D3: return 0x279;
        case 0x00F3: return 0x27A;
        case 0x015A: return 0x27B;
        case 0x015B: return 0x27C;
        case 0x0179: return 0x27D;
        case 0x017A: return 0x27E;
        case 0x017B: return 0x27F;
        case 0x017C: return 0x280;
    }
    return 0x1C0;  // невідоме → space
}

} // namespace modesp::osd
