#pragma once
// Auto-generated by tools/gen_osd_font.py --target amt630a — DO NOT EDIT
// UTF-8 codepoint → BGMAP tile-код (RAM-шрифт 0x1C0+). Невідоме → space (0x1C0).

#include <cstdint>

namespace modesp::osd {

inline uint16_t amt630a_cp_to_tile(uint32_t cp) {
    if (cp >= 0x20 && cp <= 0x7E)     return static_cast<uint16_t>(0x1C0u + (cp - 0x20));
    if (cp >= 0x0410 && cp <= 0x044F) return static_cast<uint16_t>(0x220u + (cp - 0x0410));
    switch (cp) {
        case 0x00B0: return 0x21F;
        case 0x0404: return 0x260; case 0x0406: return 0x261;
        case 0x0407: return 0x262; case 0x0490: return 0x263;
        case 0x0454: return 0x264; case 0x0456: return 0x265;
        case 0x0457: return 0x266; case 0x0491: return 0x267;
    }
    return 0x1C0;  // невідоме → space
}

} // namespace modesp::osd
