"""
Pytest wrapper що compiles і runs sequence engine host tests.

Independent of project-level tests/host/ infrastructure (entangled з stripped
refrigeration modules). Tests live у components/modesp_sequence/tests/host/
з standalone build (no CMake, just g++ direct invocation).

Discovery: ETL include path resolved on first run у same way як components/
modesp_sequence/tests/host/Makefile — checks managed_components/, then
ESP-IDF Component Manager global cache.

Tests run only якщо g++ available; skipped on systems without C++17 compiler.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).parent.parent.parent
COMPONENT = REPO_ROOT / "components" / "modesp_sequence"
HOST_TEST_DIR = COMPONENT / "tests" / "host"

# Default sources/includes — used by registry-only tests (test_action_registry,
# test_continuous_registry). Per-test overrides у TEST_CONFIG below.
SOURCES = [
    COMPONENT / "src" / "action_registry.cpp",
    COMPONENT / "src" / "continuous_registry.cpp",
]
INCLUDES = [
    COMPONENT / "include",
    REPO_ROOT / "components" / "modesp_core" / "include",
]

# Per-test build overrides. Test name → {extra_sources, extra_includes}.
# Used когда test потребує SharedState (real impl + freertos/log mocks),
# або інші cross-component sources beyond default.
TEST_CONFIG = {
    "test_builtin_actions": {
        "extra_sources": [
            COMPONENT / "src" / "builtin_actions.cpp",
            REPO_ROOT / "tests" / "host" / "shared_state_host.cpp",
        ],
        "extra_includes": [
            REPO_ROOT / "tests" / "host",
            REPO_ROOT / "tests" / "host" / "mocks",
            REPO_ROOT / "generated",
        ],
    },
    "test_modr_loader": {
        # Loader needs builtins registered to resolve cond_pool entries against
        # ActionRegistry. builtin_actions.cpp transitively pulls SharedState
        # (set_state writes through it), so test також compiles real
        # SharedState із same host mocks як test_builtin_actions.
        "extra_sources": [
            COMPONENT / "src" / "builtin_actions.cpp",
            COMPONENT / "src" / "modr_loader.cpp",
            REPO_ROOT / "tests" / "host" / "shared_state_host.cpp",
        ],
        "extra_includes": [
            REPO_ROOT / "tests" / "host",
            REPO_ROOT / "tests" / "host" / "mocks",
            REPO_ROOT / "generated",
        ],
    },
    "test_resource_arbiter": {
        # ResourceArbiter is standalone — no SharedState, no registry needed.
        # Sources: just resource_arbiter.cpp (default action_registry і
        # continuous_registry from SOURCES are also linked but unused, harmless).
        "extra_sources": [
            COMPONENT / "src" / "resource_arbiter.cpp",
        ],
    },
    "test_track_synchronization": {
        # Full engine stack: builtins + loader + arbiter + track + instance.
        # Compiles real SharedState із same host mocks як other engine tests.
        # Pre-test fixture: sync_two_tracks.modr generated by compile_scenario.py
        # (see _generate_sync_fixture fixture below).
        "extra_sources": [
            COMPONENT / "src" / "builtin_actions.cpp",
            COMPONENT / "src" / "modr_loader.cpp",
            COMPONENT / "src" / "resource_arbiter.cpp",
            COMPONENT / "src" / "sequence_track.cpp",
            COMPONENT / "src" / "sequence_instance.cpp",
            REPO_ROOT / "tests" / "host" / "shared_state_host.cpp",
        ],
        "extra_includes": [
            REPO_ROOT / "tests" / "host",
            REPO_ROOT / "tests" / "host" / "mocks",
            REPO_ROOT / "generated",
        ],
    },
    "test_sequence_engine": {
        # Engine integration test: full stack including sequence_engine.cpp
        # AND nvs_token.cpp (engine now uses serialize_token у persist_scan).
        "extra_sources": [
            COMPONENT / "src" / "builtin_actions.cpp",
            COMPONENT / "src" / "modr_loader.cpp",
            COMPONENT / "src" / "resource_arbiter.cpp",
            COMPONENT / "src" / "sequence_track.cpp",
            COMPONENT / "src" / "sequence_instance.cpp",
            COMPONENT / "src" / "sequence_engine.cpp",
            COMPONENT / "src" / "nvs_token.cpp",
            REPO_ROOT / "tests" / "host" / "shared_state_host.cpp",
        ],
        "extra_includes": [
            REPO_ROOT / "tests" / "host",
            REPO_ROOT / "tests" / "host" / "mocks",
            REPO_ROOT / "generated",
        ],
    },
    "test_nvs_token": {
        # Persistence token: needs builtins (registered conditions used by
        # any cond_pool entries в loaded scenario), modr_loader (validate fixture),
        # sequence_instance (instance_start to populate runtime), nvs_token impl.
        "extra_sources": [
            COMPONENT / "src" / "builtin_actions.cpp",
            COMPONENT / "src" / "modr_loader.cpp",
            COMPONENT / "src" / "resource_arbiter.cpp",
            COMPONENT / "src" / "sequence_track.cpp",
            COMPONENT / "src" / "sequence_instance.cpp",
            COMPONENT / "src" / "nvs_token.cpp",
            REPO_ROOT / "tests" / "host" / "shared_state_host.cpp",
        ],
        "extra_includes": [
            REPO_ROOT / "tests" / "host",
            REPO_ROOT / "tests" / "host" / "mocks",
            REPO_ROOT / "generated",
        ],
    },
}


def _find_gpp() -> str | None:
    """Locate g++ executable. Returns full path or None if not found."""
    # Try PATH first
    gpp = shutil.which("g++")
    if gpp:
        return gpp
    # Try common Windows locations
    candidates = [
        "C:/msys64/ucrt64/bin/g++.exe",
        "C:/msys64/mingw64/bin/g++.exe",
        "/usr/bin/g++",
    ]
    for c in candidates:
        if Path(c).exists():
            return c
    return None


def _find_etl_include() -> Path | None:
    """Find ETL header path (managed_components first, then ESP-IDF cache)."""
    managed = REPO_ROOT / "managed_components" / "marcel-cd__etlcpp" / "etl" / "include"
    if managed.exists():
        return managed

    # Windows ESP-IDF Component Manager cache
    if os.name == "nt":
        cache_base = Path(os.environ.get("LOCALAPPDATA", "")) / "Espressif" / "ComponentManager" / "Cache"
    else:
        cache_base = Path.home() / ".espressif" / "ComponentManager" / "Cache"

    if cache_base.exists():
        # Glob for marcel-cd__etlcpp_*/etl/include
        matches = sorted(cache_base.glob("*/marcel-cd__etlcpp_*/etl/include"), reverse=True)
        if matches:
            return matches[0]

    return None


def _compile_test(name: str, gpp: str, etl_include: Path) -> Path:
    """Compile a single host test executable. Returns path to binary."""
    src = HOST_TEST_DIR / f"{name}.cpp"
    if not src.exists():
        raise FileNotFoundError(f"Test source not found: {src}")

    cfg = TEST_CONFIG.get(name, {})
    sources = list(SOURCES) + list(cfg.get("extra_sources", []))
    includes = list(INCLUDES) + list(cfg.get("extra_includes", []))

    output = HOST_TEST_DIR / f"{name}.exe"
    cmd = [
        gpp,
        "-std=c++17", "-Wall", "-Wno-unused-parameter", "-Wno-unused-variable",
        "-DETL_NO_PROFILE_HEADER", "-DHOST_BUILD=1",
        "-O0", "-g",
    ]
    for inc in includes:
        cmd.extend(["-I", str(inc)])
    cmd.extend(["-I", str(etl_include)])
    cmd.append(str(src))
    cmd.extend(str(s) for s in sources)
    cmd.extend(["-o", str(output)])

    # IMPORTANT (Windows MSYS2 toolchain): cc1plus.exe (g++ child) needs runtime
    # DLLs (libstdc++-6.dll, libgcc_s_seh-1.dll, ...) from the same bin folder
    # as g++.exe. If that dir isn't on PATH, the child loads zero DLLs, exits
    # silently, and parent g++ reports nothing (returncode 1, no stderr).
    # Discovered empirically Step 7. We prepend g++'s directory to PATH for
    # subprocess invocation so DLL resolution succeeds.
    env = os.environ.copy()
    gpp_dir = str(Path(gpp).parent)
    env["PATH"] = gpp_dir + os.pathsep + env.get("PATH", "")

    result = subprocess.run(
        cmd, capture_output=True, text=True, stdin=subprocess.DEVNULL, env=env
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Compilation failed (returncode={result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return output


# ── Fixtures ──


@pytest.fixture(scope="session")
def gpp():
    p = _find_gpp()
    if p is None:
        pytest.skip("g++ not found — skipping C++ host tests")
    return p


@pytest.fixture(scope="session")
def etl_include():
    p = _find_etl_include()
    if p is None:
        pytest.skip("ETL not found — run idf.py build first to download dependencies")
    return p


@pytest.fixture(scope="session", autouse=True)
def _generate_sync_fixture():
    """Compile sync_two_tracks.modr from JSON manifest before any test runs.

    Test test_track_synchronization_host loads це fixture from disk; without
    autouse fixture, manual compile step would be required і fragile.
    Idempotent: regenerates на every test session, so manifest edits propagate.
    """
    fixtures = REPO_ROOT / "tools" / "tests" / "fixtures" / "scenarios"
    recipe = fixtures / "sync_two_tracks_recipe.json"
    output = fixtures / "sync_two_tracks.modr"
    if not recipe.exists():
        return  # fixture не exists — test will skip itself
    compiler = REPO_ROOT / "tools" / "compile_scenario.py"
    cmd = [
        sys.executable, str(compiler),
        "--recipe", str(recipe),
        "--output", str(output),
        "--quiet",
    ]
    subprocess.run(cmd, check=False, stdin=subprocess.DEVNULL)


# ── Tests ──


def _run_host_test(name: str, gpp: str, etl_include: Path):
    """Helper: compile і run a host test binary, assert success.

    Test binary також needs MSYS2 runtime DLLs on PATH (linked dynamically
    against libstdc++-6.dll, libgcc_s_seh-1.dll, etc.). Without DLLs available,
    the binary fails to start (exit 0xC0000139 STATUS_ENTRYPOINT_NOT_FOUND or
    silent abort) — we propagate g++'s bin dir into PATH for runs."""
    binary = _compile_test(name, gpp, etl_include)
    env = os.environ.copy()
    env["PATH"] = str(Path(gpp).parent) + os.pathsep + env.get("PATH", "")
    result = subprocess.run(
        [str(binary)], capture_output=True, text=True, stdin=subprocess.DEVNULL, env=env
    )
    assert result.returncode == 0, (
        f"Host test {name} FAILED:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    assert "passed" in result.stdout
    assert "0 failed" in result.stdout, f"Some sub-tests failed:\n{result.stdout}"


def test_action_registry_host(gpp, etl_include):
    """ActionRegistry singleton, register/find для actions і conditions, collision
    detection, djb2 invariants. ~12 internal test cases у one binary."""
    _run_host_test("test_action_registry", gpp, etl_include)


def test_continuous_registry_host(gpp, etl_include):
    """ContinuousRegistry singleton, factory registration, create() invocation,
    collision detection, null factory rejection. ~11 internal test cases."""
    _run_host_test("test_continuous_registry", gpp, etl_include)


def test_builtin_actions_host(gpp, etl_include):
    """Built-in actions (log, set_state, wait_ms) і conditions (time_elapsed_ms,
    state_key_eq/ne/lt/gt/le/ge, state_key_in_range, state_key_changed,
    time_of_day_eq). ~30 internal test cases. Uses real SharedState із host
    mocks (freertos_mock.h, esp_log_mock.h)."""
    _run_host_test("test_builtin_actions", gpp, etl_include)


def test_modr_loader_host(gpp, etl_include):
    """`.modr` binary loader: positive (golden minimal_v1 fixture) і ~20
    corruption variants forcing each EngineError code (INVALID_FILE,
    UNSUPPORTED_VERSION, CRC_MISMATCH, BUFFER_OVERFLOW, INVALID_TRANSITION,
    TOO_MANY_TRACKS). Includes CRC32 ISO-HDLC golden vector."""
    _run_host_test("test_modr_loader", gpp, etl_include)


def test_resource_arbiter_host(gpp, etl_include):
    """ResourceArbiter ISA-88 §5.3: scenario-scope acquire/release atomicity,
    phase-scope try-acquire з rollback, cross-instance contention, mixed-scope
    coexistence, idempotent re-grant. ~17 sub-tests."""
    _run_host_test("test_resource_arbiter", gpp, etl_include)


def test_track_synchronization_host(gpp, etl_include):
    """Cross-track sync via SharedState (ADR-0003 tick-order semantics).
    Loads sync_two_tracks.modr fixture (auto-compiled by session fixture) і
    drives instance_tick to completion: track 0 writes test.signal=true,
    track 1 transitions when state_key_eq fires. Validates that the writer
    track's update is visible to the watcher track within reasonable tick budget."""
    _run_host_test("test_track_synchronization", gpp, etl_include)


def test_sequence_engine_host(gpp, etl_include):
    """SequenceEngine multi-instance dispatcher: load_buffer/load_path lifecycle,
    start/pause/resume/abort transitions, on_update tick driving scenario до
    COMPLETED, slot exhaustion (NO_SLOT), unload-then-reload, multi-instance
    independence, diagnostic accessors. ~16 sub-tests."""
    _run_host_test("test_sequence_engine", gpp, etl_include)


def test_nvs_token_host(gpp, etl_include):
    """Persistence token: serialize/deserialize round-trip restores phase_idx +
    elapsed_ms (final state PAUSED per plan Q7), magic/version/CRC corruption →
    specific EngineError codes, scenario_id mismatch rejected (stale token from
    previous recipe), CRC16-CCITT golden vector. ~10 sub-tests."""
    _run_host_test("test_nvs_token", gpp, etl_include)
