<script>
  import { pages } from "../stores/ui.js";
  import { state } from "../stores/state.js";
  import { t } from "../stores/i18n.js";
  import { isVisible } from "../lib/visibility.js";
  import Card from "../components/Card.svelte";
  import WidgetRenderer from "../components/WidgetRenderer.svelte";

  // Dashboard page from ui.json (generated by _dashboard_page())
  $: dashPage = ($pages || []).find(p => p.id === "dashboard");
  $: cards = dashPage ? dashPage.cards || [] : [];
</script>

<div class="dashboard">
  {#each cards as card}
    {@const visibleWidgets = (card.widgets || []).filter(w => isVisible(w, $state))}
    {#if visibleWidgets.length > 0}
      <Card title={$t[card.title] || card.title} subtitle={$t[card.subtitle] || card.subtitle} icon={card.icon}>
        <div class="card-widgets">
          {#each visibleWidgets as widget (widget.key)}
            <WidgetRenderer {widget} />
          {/each}
        </div>
      </Card>
    {/if}
  {/each}

  {#if cards.length === 0}
    <div class="empty">
      <p>No modules configured. Add modules to <code>project.json</code> and rebuild.</p>
    </div>
  {/if}
</div>

<style>
  .dashboard {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  .card-widgets {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  .empty {
    text-align: center;
    padding: 3rem;
    color: var(--text-secondary, #666);
  }
  .empty code {
    background: var(--bg-tertiary, #f0f0f0);
    padding: 0.2rem 0.4rem;
    border-radius: 4px;
  }
</style>
